### ISSUE TITLE
Fragile Glass & Thin Ice Text Glitch

### ISSUE THREAD

**Issue by AwesomeNinja886** [stal111/Weapon-Craftery#1]
I have the [Fragile Glass & Thin Ice](https://www.curseforge.com/minecraft/mc-mods/fragile-glass-and-thin-ice) mod for 1.14.4 and the stats are... to say the least... glitched.

Above Enchantability and below Durability it says this exact text:

STAINED FRAGILE GLASS PANE

Why does it do this, and can it be fixed?

**Comment by stal111** [comment]
Could you please include a screenshot of the issue?

**Comment by AwesomeNinja886** [comment]
My other computer (the one I play MC on) refuses to do Bluetooth transfer, so I can't provide a screenshot.

**Comment by stal111** [comment]
Fixed in weapon_craftery-1.14.4-1.0-Beta-2
