### ISSUE TITLE
[Bug] I can't create sticks with crafting box or inventory

### ISSUE THREAD

**Issue by trukulo** [stal111/Weapon-Craftery#4]
It just doesn't show the stick.

I'm using Vanilla Minecraft 1.14.4.

I added the mod in mods folder.

Maybe I'm missing texture pack or something?

![Screen Shot 2019-08-08 at 10 12 25](https://user-images.githubusercontent.com/51512527/62689725-a8065e00-b9cb-11e9-9e54-c7547c304e86.png)

**Comment by stal111** [comment]
Fixed in weapon_craftery-1.14.4-1.0-Beta-3
